<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SysSuite.Core.Abstractions\SysSuite.Core.Abstractions.csproj" />
    <ProjectReference Include="..\SysSuite.Interop\SysSuite.Interop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
