<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SysSuite.Core.Abstractions\SysSuite.Core.Abstractions.csproj" />
    <ProjectReference Include="..\SysSuite.Interop\SysSuite.Interop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\known-software-profiles.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\rules\clean-temp.json" Link="rules\clean-temp.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SysSuite.Tests" />
  </ItemGroup>
</Project>